### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by withdongs** [flowplayer/flowplayer-android-sdk-demo#2]
I cloned it with the master branch. It failed when building with Android Studio. I'd appreciate if you could check the log and let me know where to fix it.

> Task :app:compileDebugKotlin FAILED
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.flowplayer.android.common.player.BasePlayer, unresolved supertypes: com.google.android.exoplayer2.Player$EventListener, com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener, com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener

e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

**Comment by VikiBDev** [comment]
Hi! 

I'm the new maintainer for Flowplayer's Android SDK. I'm going to close this issue as we just released a major update (v2.0.0), and this issue isn't relevant anymore. Please open a new one if you can't run the new version!
